run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - unused
    - goconst
    - gocyclo
    - revive
  disable:
    - gochecknoglobals

linters-settings:
  gocyclo:
    min-complexity: 12
  revive:
    confidence: 0.8
  errcheck:
    exclude-functions:
      - fmt.Printf
      - fmt.Fprintf
      - fmt.Println

issues:
  max-same-issues: 0
  max-per-linter: 0
  exclude-rules:
    - linters:
        - errcheck
      text: "Close\\(err\\)"

