warn = [
  "clippy::pedantic",
  "clippy::nursery"
]

deny = [
  "clippy::unwrap_used",
  "clippy::expect_used",
  "clippy::todo"
]

allow = [
  "clippy::module_name_repetitions"
]

msrv = "1.80"
workspace_lints = "warn"

