edition = "2021"
newline_style = "Unix"
use_small_heuristics = "Max"
max_width = 100
hard_tabs = false
wrap_comments = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
normalize_doc_attributes = true

