target-version = "py312"
line-length = 100
fix = false
unsafe-fixes = false

[lint]
select = ["E", "F", "I", "UP", "B", "DTZ", "PL", "RUF"]
ignore = ["E203", "E501"]
preview = true

[lint.per-file-ignores]
"tests/**/*.py" = ["S101"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false

